---
title: 'Getting involved in Frederickson Lab research as an undergraduate student'
author: "Megan Frederickson"
date: "12/01/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## WELCOME!

Undergraduate student researchers are valued members of the [Frederickson Lab](http://mutualism.ca). We are happy you are thinking of getting involved in our lab's research!

Every year, the lab gets a large number of emails from undergraduate students asking about research opportunities in the lab. 

The good news is that there are many different programs at the University of Toronto that support undergraduate student researchers. 

The bad news is that students are not always aware of all the different programs, and sometimes find them hard to navigate, as each program has its own deadlines, eligibility requirements, and procedures. 

This document is intended to be a brief guide to becoming an undergraduate student researcher in the Frederickson Lab. The Department of Ecology and Evolutionary Biology also has [a helpful slide deck](https://docs.google.com/presentation/d/1dT8qmbnDMnP6IeaRHRbfRPwzXYWYPmxDo1n27dWhwjY/edit#slide=id.gc55ddffe75_0_1483) that describes most of the same opportunities in more detail. 

### Work-study 

Work-study positions are paid, part-time jobs on campus. The Frederickson Lab usually has eight work-study positions a year: four during the summer, and four during the academic year (i.e., the fall and winter semesters). These positions are paid at $15/hr plus 10% benefits with a maximum of 15 hrs/week and 100 or 200 hours total for the summer or fall-winter cycles, respectively. 

In our lab, work-study students do not undertake their own research projects. Instead, they support other researchers in the lab by doing a range of essential tasks such as autoclaving, washing glassware or plant pots or the like, making media, taking care of live organisms (mainly plants, sometimes insects or microbes), cleaning out and organizing lab fridges and freezers, and so on. 

During the COVID-19 pandemic, we have also had work-study students work remotely assembling datasets from the published literature or analyzing and extracting data from images of experiments. 

We usually hire work-study students in September for the academic year and in April or early May for the summer. Work-study job ads are posted on the University of Toronto's [Career Learning Network](https://clnx.utoronto.ca/students/wspublicstudents.htm) website. Applications are also submitted through the [CLN](https://clnx.utoronto.ca) website. 

### Research opportunities program (ROP)

ROP students are 2nd- or 3rd-year students who get course credit for doing research in the Frederickson Lab. Usually the Frederickson Lab has one or two ROP students a year who work on a pre-defined research project, often under the day-to-day supervision of a graduate student or postdoc. ROP students also have to write a research proposal and final report as part of their course. The specific projects that ROP students work on change every year, and interested students apply in late February for either the coming summer or the following academic year. ROP students often present their research at an annual research fair in March. In the Frederickson Lab, some ROP students have gone on to publish their results in peer-reviewed journal articles.

The program is administered by the Faculty of Arts and Science, and there is a lot more information available on the [Research Opportunities Program](https://www.artsci.utoronto.ca/current/academics/research-opportunities/research-opportunities-program) website, including key program dates, eligibility rules, and descriptions of specific ROP projects. 

### 4th-year independent research projects

4th-year students, and some 3rd-year students, can also do an independent research project for course credit by taking [EEB498](https://artsci.calendar.utoronto.ca/course/eeb498y1) (or [EEB397](https://artsci.calendar.utoronto.ca/course/eeb397y1), [EEB497](https://artsci.calendar.utoronto.ca/course/eeb497h1), or [EEB499](https://artsci.calendar.utoronto.ca/course/eeb499y1)). These are generally akin to an honours thesis or a capstone research project. Most students take EEB498 as a full-year course in their final year of undergrad, although half-year and summer research project courses are a possibility. Research project students develop and carry out their own independent research project, again often with input and supervision from a graduate student or postdoc in the lab. They usually present their research at the department's annual undergraduate research fair in April, and some have gone on to publish their results in peer-reviewed journal articles.

Interested students should get in touch with Prof. Megan Frederickson by email, and must submit an application form to the department in March for the summer semester or in July for the following academic year. More information is available on the [Dept. of Ecology and Evolutionary Biology](https://eeb.utoronto.ca/education/undergraduate/research-courses-2/) website.

### Summer research awards

There are several competitive programs that offer awards to undergraduate students to do research over the summer months. The best known of these is the [NSERC Undergraduate Student Research Awards](https://www.nserc-crsng.gc.ca/students-etudiants/ug-pc/usra-brpc_eng.asp) program, which in EEB pays $7500 for 16 weeks of full-time work in the summer. Similar programs include the [Center for Global Change Science internships](https://cgcs.physics.utoronto.ca/internships/). Applications for these programs are due in late February or early March for the upcoming summer. All of these programs are described in more detail on the [EEB Department](https://eeb.utoronto.ca/education/undergraduate/scholarships-and-awards/) website. Although NSERC USRAs are federally funded, the application process and administration of these awards is handled locally by the department. 

### Volunteering

In the past, the Frederickson Lab has accepted undergraduate student volunteers. However, not all students can afford to work for free, and it is not fair to offer opportunities to gain research experience only to students with enough financial resources to pursue unpaid positions. For this reason, we encourage students to consider one of the above options instead. All the programs listed above offer either pay or course credit to undergraduate student researchers. We will consider volunteers only when unusual lab needs or student circumstances arise. 
